---
- name: add a new string at the end of the file
  lineinfile: dest=/etc/haproxy/haproxy.cfg
              regexp=''
              insertafter=EOF
              line="        server {{item}} {{ hostvars[item]['ansible_ec2_local_ipv4']}}:1337 check \n"
  with_items: groups.slave_dispatcher
