---

- name: Install ES
  pacman: name=elasticsearch
          state=installed

- name: Create ES data directory 
  file: path=/data/elasticsearch/ state=directory
        owner=elasticsearch group=elasticsearch mode=0755

- name: Enable ES service
  service: name=elasticsearch.service
           enabled=yes
           state=started

- name: Install ES cloud-aws plugin
  shell: /usr/bin/elasticsearch-plugin -install elasticsearch/elasticsearch-cloud-aws/2.3.0
  notify: restart elasticsearch

- name: Install ES Marvel plugin
  shell: /usr/bin/elasticsearch-plugin -install elasticsearch/marvel/latest
  notify: restart elasticsearch

- name: Install ES Paramedic plugin
  shell: /usr/bin/elasticsearch-plugin -install karmi/elasticsearch-paramedic
  notify: restart elasticsearch

- name: Install ES Head plugin
  shell: /usr/bin/elasticsearch-plugin -install mobz/elasticsearch-head
  notify: restart elasticsearch

- name: Copy ES settings
  template: src=./elasticsearch.yml.j2
            dest=/etc/elasticsearch/elasticsearch.yml
            owner=root group=root mode=0644
  notify: restart elasticsearch

