---

- name: Define record based on environment
  set_fact:
    dns_record: "{{production_url}}"
  when: env=="production"

- name: Define record based on environment
  set_fact:
    dns_record: "{{staging_url}}"
  when: env=="staging"

- debug: msg="hostvars {{hostvars}}" 
- debug: msg="{{hostvars['127.0.0.1']}}"

- name: Update DNS, delete old, add new
  local_action:
    module: route53
    command: create
    overwrite: yes
    zone: pandastrike.com
    record: "{{dns_record}}"
    type: A
    ttl: 60
    value: "{{hostvars['127.0.0.1']['ec2']['instances'][0]['public_ip']}}"

#value: "{{hostvars[inventory_hostname]['ansible_ec2_public_ipv4']}}"
