---

- name: Install required packages
  pacman: name=git,nodejs
          state=installed

- name: Install CoffeeScript
  command: npm install -g coffee-script
           creates=/usr/bin/coffee

- name: Upload SSH key
  copy: src=~/.ssh/gh-shopperr-id_rsa
        dest=/root/.ssh/id_rsa
        mode=0600

- name: Git clone
  git: repo={{repo_url}}
       dest={{repo_dir}}
       version={{branch}}
       depth=1
       accept_hostkey=yes

- name: Run NPM install
  command: npm install
           chdir={{crawler_dir}}

- name: Upload crawler worker config
  template: src=./crawler-worker-production-config.cson.j2
            dest={{crawler_env_dir}}config.cson
            owner=root group=root mode=0644

- name: Upload crawler worker service 1
  template: src=./crawler-worker.service.j2
            dest=/etc/systemd/system/crawler-worker-1.service
            owner=root group=root mode=0644

- name: Enable crawler worker service 1
  service: name=crawler-worker-1.service
           enabled=yes
           state=started

- name: Upload crawler worker service 2
  template: src=./crawler-worker.service.j2
            dest=/etc/systemd/system/crawler-worker-2.service
            owner=root group=root mode=0644

- name: Enable crawler worker service 2
  service: name=crawler-worker-2.service
           enabled=yes
           state=started

