---

- name: Get instance data from the metadata servers in EC2
  ec2_facts:

- name: Install required Arch packages
  pacman: name=git,nodejs
          state=installed

- name: Install CoffeeScript
  command: npm install -g coffee-script
           creates=/usr/bin/coffee

- name: Upload SSH key
  copy: src=~/.ssh/gh-shopperr-id_rsa
        dest=/root/.ssh/id_rsa
        mode=0600

- name: Git clone
  git: repo={{repo_url}}
       dest={{repo_dir}}
       version={{branch}}
       depth=1
       accept_hostkey=yes

- name: Run NPM install
  command: npm install
           chdir={{crawler_dir}}

- name: Upload crawler manager config
  template: src=./crawler-manager-production-config.cson.j2
            dest={{crawler_env_dir}}config.cson
            owner=root group=root mode=0644

- name: Upload crawler manager service
  template: src=./crawler-manager.service.j2
            dest=/etc/systemd/system/crawler-manager.service
            owner=root group=root mode=0644

- name: Enable crawler manager service
  service: name=crawler-manager.service
           enabled=yes
           state=started

